[validation.h] Fix CountIterator interface
Before this change, the following line in an input validator

```cpp
v.read_integer("x", 0, 42, Unique);
```

would yield a compilation error

```plain
<snip>/include/c++/14.3.0/bits/stl_algobase.h:514:64: error: no type named ‘iterator_category’ in ‘struct std::iterator_traits<Validator::gen_number<long long int, UniqueTag>(const std::string&, long long int, long long int, UniqueTag)::CountIterator>’
  514 |       typedef typename iterator_traits<_II>::iterator_category _Category;
```

The definition of CountIterator has multiple problems:
1. It does not declare the type aliases required for any of the iterator
   concepts.
2. When incrementing, it should return another iterator, not a value.
   This probably worked coincidentally because the number can be
   converted back to an iterator immediately
3. Dereference and comparison were non-const only.

I fixed all of these and added a static assert for forward_iterator. I
am not sure whether this is the most fitting iterator class, but it
seemed appropriate. I am also not sure about difference_type, but I
think this is used for counting up in `std::distance`. I think that this
could also be a random access iterator, but I don't know if that makes a
significant difference anywhere.